failover_command = '/opt/bitnami/scripts/failover.sh %d %h %p %D %m %H %M %P %r %R'
follow_primary_command = '/opt/bitnami/scripts/follow_primary.sh %d %h %p %D %m %H %M %P %r %R'
backend_data_directory0 = '/bitnami/postgresql/data'
backend_data_directory1 = '/bitnami/postgresql/data'
backend_data_directory2 = '/bitnami/postgresql/data'