failover_command = '/opt/bitnami/scripts/failover.sh %d %h %p %D %m %H %M %P %r %R'
follow_primary_command = '/opt/bitnami/scripts/follow_primary.sh %d %h %p %D %m %H %M %P %r %R'
backend_data_directory0 = '/bitnami/postgresql/data'
backend_data_directory1 = '/bitnami/postgresql/data'
backend_data_directory2 = '/bitnami/postgresql/data'
pcp_listen_addresses = '*'
pcp_port = 9898

# log_min_messages = debug1
# log_statement = all
# debug_level = 3
failover_on_backend_error = off
sr_check_period = 10

health_check_period = 5
health_check_timeout = 30
# health_check_user = 'repl_user'
health_check_password = ''
health_check_max_retries = 3

# thuc hien failback
recovery_user = 'postgres'
recovery_password = '1234'
recovery_1st_stage_command = 'opt/bitnami/scripts/recovery_1st_stage.sh'
   