version: '3.8'
# doi voi app web trung binh nen cho len 2 - 3 slave thoi
services:
  pg-master:
    image: pgserver
    container_name: pg-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_pass
      - POSTGRESQL_PASSWORD=1234
    ports:
      - "5433:5432"
    volumes: 
      - ./id_rsa_pgpool.pub:/tmp/id_rsa_pgpool.pub
      - ./custom.conf:/bitnami/postgresql/conf/conf.d/custom.conf
      - ./custom.conf:/bitnami/postgresql/conf/conf.d/postgresql-custom.conf
    networks:
      - pgnet
          
  pg-slave:
    image: pgserver
    container_name: pg-slave
    depends_on:
      - pg-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=pg-master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_pass
      - POSTGRESQL_PASSWORD=1234
    ports:
      - "5434:5432"
    volumes: 
      - ./id_rsa_pgpool.pub:/tmp/id_rsa_pgpool.pub
      - ./custom.conf:/bitnami/postgresql/conf/conf.d/custom.conf
      - ./custom.conf:/bitnami/postgresql/conf/conf.d/postgresql-custom.conf
    networks:
      - pgnet

  pg-slave-1:
    image: pgserver
    container_name: pg-slave-1
    depends_on:
      - pg-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=pg-master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_pass
      - POSTGRESQL_PASSWORD=1234
    ports:
      - "5435:5432"
    volumes: 
      - ./id_rsa_pgpool.pub:/tmp/id_rsa_pgpool.pub
      - ./custom.conf:/bitnami/postgresql/conf/conf.d/custom.conf
      - ./custom.conf:/bitnami/postgresql/conf/conf.d/postgresql-custom.conf
    networks:
      - pgnet

  pgpool:
    image: pgpool
    container_name: pgpool
    depends_on:
      - pg-master
      - pg-slave
      - pg-slave-1
    ports:
      - "9999:5432"
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-master:5432,1:pg-slave:5432,2:pg-slave-1:5432
      - PGPOOL_SR_CHECK_USER=postgres
      - PGPOOL_SR_CHECK_PASSWORD=1234
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=1234
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=admin
      - PGPOOL_NUM_INIT_CHILDREN=100
      - PGPOOL_MAX_POOL=2
      - PGPOOL_USER_CONF_FILE=/cus_pgpool.conf
    volumes:
      - ./failover.sh:/opt/bitnami/scripts/failover.sh
      - ./follow_primary.sh:/opt/bitnami/scripts/follow_primary.sh
      - ./cus_pgpool.conf:/cus_pgpool.conf
      - /var/run/docker.sock:/var/run/docker.sock
      - ./id_rsa_pgpool:/root/.ssh/id_rsa_pgpool
      - ./id_rsa_pgpool:/home/postgres/.ssh/id_rsa_pgpool
      - ./custom.conf:/bitnami/postgresql/conf/conf.d/custom.conf
      - ./custom.conf:/bitnami/postgresql/conf/conf.d/postgresql-custom.conf
    networks:
      - pgnet


networks:
  pgnet:

