version: '3.8'
# doi voi app web trung binh nen cho len 2 - 3 slave thoi
services:
  pg-master:
    image: bitnamilegacy/postgresql:latest
    container_name: pg-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_pass
      - POSTGRESQL_PASSWORD=1234
    ports:
      - "5433:5432"
    volumes: 
      - ./id_rsa_pgpool.pub:/tmp/id_rsa_pgpool.pub
      # - ./pg_master_data:/bitnami/postgresql

  pg-slave:
    image: pgserver
    container_name: pg-slave
    depends_on:
      - pg-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=pg-master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_pass
      - POSTGRESQL_PASSWORD=1234
    ports:
      - "5434:5432"
    volumes: 
      - ./id_rsa_pgpool.pub:/tmp/id_rsa_pgpool.pub
      # - ./pg_slave_data:/bitnami/postgresql

  pgpool:
    image: pgpool
    container_name: pgpool
    depends_on:
      - pg-master
      - pg-slave
    ports:
      - "9999:5432"
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-master:5432,1:pg-slave:5432
      # - PGPOOL_BACKEND_NODES=0:pg-master:5432:/bitnami/postgresql/data,1:pg-slave:5432:/bitnami/postgresql/data
      - PGPOOL_SR_CHECK_USER=postgres
      - PGPOOL_SR_CHECK_PASSWORD=1234
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=1234
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=admin
      - PGPOOL_NUM_INIT_CHILDREN=100
      - PGPOOL_MAX_POOL=2
      - PGPOOL_USER_CONF_FILE=/cus_pgpool.conf
    volumes:
      - ./failover.sh:/opt/bitnami/scripts/failover.sh
      - ./cus_pgpool.conf:/cus_pgpool.conf
      - /var/run/docker.sock:/var/run/docker.sock
      - ./id_rsa_pgpool:/root/.ssh/id_rsa_pgpool
      - ./id_rsa_pgpool:/home/postgres/.ssh/id_rsa_pgpool

