scope: postgres-cluster
name: node2

restapi:
  listen: 0.0.0.0:8008
  connect_address: node2:8008

etcd:
  hosts: etcd:2379

postgresql:
  listen: 0.0.0.0:5432
  connect_address: node2:5432
  data_dir: /var/lib/postgresql/data

  authentication:
    superuser:
      username: postgres
      password: postgres
    replication:
      username: repl
      password: repl

  parameters:
    max_connections: 100
    shared_buffers: 256MB
  pg_hba:
    - host all all 0.0.0.0/0 md5
    - host replication repl 0.0.0.0/0 md5

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
