scope: postgres-cluster
name: node1

restapi:
  listen: 0.0.0.0:8008
  connect_address: node1:8008

etcd:
  hosts: etcd:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      hot_standby: on 
      max_wal_senders: 10
      max_replication_slots: 10
      
  initdb:
    - encoding: UTF8
    - data-checksums

  users:
    postgres: 
      password: 1234
      options:
        - superuser
        - createdb
    repl:
      password: repl
      options:
        - replication

postgresql:
  listen: 0.0.0.0:5432
  connect_address: node1:5432
  data_dir: /var/lib/postgresql/data

  authentication:
    superuser:
      username: postgres
      password: postgres
    replication:
      username: repl
      password: repl

  parameters:
    max_connections: 100
    shared_buffers: 256MB
  pg_hba:
    - host all all 0.0.0.0/0 md5
    - host replication repl 0.0.0.0/0 md5

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
